kind: Namespace
apiVersion: v1
metadata:
  name: desplieguebanquito
  uid: a79753ac-eef1-4e7a-abb3-b71777d27f26
  resourceVersion: '926064'
  creationTimestamp: '2024-03-13T19:38:53Z'
  labels:
    kubernetes.io/metadata.name: desplieguebanquito
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2024-03-13T19:38:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:kubernetes.io/metadata.name: {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
