apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue
  labels:
    app: despliegue
  namespace: namespace-workflow-1710359259766
spec:
  replicas: 1
  selector:
    matchLabels:
      app: despliegue
  template:
    metadata:
      labels:
        app: despliegue
    spec:
      containers:
        - name: despliegue
          image: banquitostageacr.azurecr.io/image-workflow-1710359259766:latest
          ports:
            - containerPort: 8080